### ISSUE TITLE
Add ability to inspect a link with parameter 

### ISSUE THREAD

**Issue by azerozvn** [BKWLD/lightkeeper#12]
PSI seems to run fine with GTM testing site, but lightkeeper does not.
For example: https://6362b9a5f89a46000a1c9dac--dripdrop-dev.netlify.app/?gtm_debug=1667420246306

**Comment by weotch** [comment]
Maybe you just need to surround the URL in quotes?

<img width="566" alt="image" src="https://user-images.githubusercontent.com/77567/199850187-23a9e404-93aa-47ff-851e-366ad1c646c0.png">

**Comment by azerozvn** [comment]
I didn't know that, it works! :+1:
